#!/bin/bash

cat <<EOF > .env
APP_NAME=Laravel
APP_ENV=${APP_ENV}
APP_KEY=${APP_KEY}
APP_DEBUG=false
APP_URL=${APP_URL:-http://localhost:8080}

LOG_CHANNEL=stack

DB_CONNECTION=${DB_CONNECTION}
DB_HOST=${DB_HOST:-127.0.0.1}
DB_PORT=${DB_PORT:-5432}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

BROADCAST_DRIVER=${BROADCAST_DRIVER}
PUSHER_APP_ID=${PUSHER_APP_ID}
PUSHER_APP_KEY=${PUSHER_APP_KEY}
PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
PUSHER_HOST=${PUSHER_HOST}
PUSHER_PORT=${PUSHER_PORT}
PUSHER_SCHEME=${PUSHER_SCHEME}

EOF

php artisan config:clear
php artisan config:cache

php artisan migrate --force

exec "$@"